OC-140: Implementing new UI of Add Address screen, Edit Address and my Address.
objectorientguy/onecart_user_app pull request #103
Opened 2023-09-16 12:45 UTC by AakanshaThakur

2023-09-18 07:35 UTC, Aditi-005 requested changes

2023-09-18 07:35 UTC, Aditi-005 commented on lib/Screens/address/widget/address_filterchip_widget.dart
> +                  log('onTap===============>$selectedType');
remove all log

2023-09-18 07:35 UTC, Aditi-005 commented on lib/Screens/orders/widgets/item_orders_expansiontile.dart
>  // import 'package:flutter/material.dart';
remove commented code or delete this file

2023-09-18 07:35 UTC, Aditi-005 commented on lib/blocs/address_bloc/address_bloc.dart
> +    log('address post===========>${event.addAddress}');
remove all logs and commented code

2023-09-21 09:53 UTC, 404ajayreddy requested changes

2023-09-21 09:53 UTC, 404ajayreddy commented on lib/Screens/address/widget/address_form.dart
> +                        log('onChanged=========>${saveAddress['address_name'].toString()}');
remove logs

2023-09-21 10:58 UTC, 404ajayreddy approved these changes

2023-09-21 11:04 UTC, merged